export const COUNTRIES = [
  { code: "AF", country: "Afghanistan", flag: "🇦🇫", dialCode: "93", fullCode: "+93", minLength: 9, maxLength: 9, currency: "AFN", symbol: "؋" },
  { code: "AL", country: "Albania", flag: "🇦🇱", dialCode: "355", fullCode: "+355", minLength: 9, maxLength: 9, currency: "ALL", symbol: "L" },
  { code: "DZ", country: "Algeria", flag: "🇩🇿", dialCode: "213", fullCode: "+213", minLength: 9, maxLength: 9, currency: "DZD", symbol: "د.ج" },
  { code: "AS", country: "American Samoa", flag: "🇦🇸", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "USD", symbol: "$" },
  { code: "AD", country: "Andorra", flag: "🇦🇩", dialCode: "376", fullCode: "+376", minLength: 6, maxLength: 6, currency: "EUR", symbol: "€" },
  { code: "AO", country: "Angola", flag: "🇦🇴", dialCode: "244", fullCode: "+244", minLength: 9, maxLength: 9, currency: "AOA", symbol: "Kz" },
  { code: "AI", country: "Anguilla", flag: "🇦🇮", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "XCD", symbol: "$" },
  { code: "AG", country: "Antigua and Barbuda", flag: "🇦🇬", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "XCD", symbol: "$" },
  { code: "AR", country: "Argentina", flag: "🇦🇷", dialCode: "54", fullCode: "+54", minLength: 10, maxLength: 11, currency: "ARS", symbol: "$" },
  { code: "AM", country: "Armenia", flag: "🇦🇲", dialCode: "374", fullCode: "+374", minLength: 8, maxLength: 8, currency: "AMD", symbol: "֏" },
  { code: "AW", country: "Aruba", flag: "🇦🇼", dialCode: "297", fullCode: "+297", minLength: 7, maxLength: 7, currency: "AWG", symbol: "ƒ" },
  { code: "AU", country: "Australia", flag: "🇦🇺", dialCode: "61", fullCode: "+61", minLength: 9, maxLength: 9, currency: "AUD", symbol: "$" },
  { code: "AT", country: "Austria", flag: "🇦🇹", dialCode: "43", fullCode: "+43", minLength: 10, maxLength: 13, currency: "EUR", symbol: "€" },
  { code: "AZ", country: "Azerbaijan", flag: "🇦🇿", dialCode: "994", fullCode: "+994", minLength: 9, maxLength: 9, currency: "AZN", symbol: "₼" },
  { code: "BS", country: "Bahamas", flag: "🇧🇸", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "BSD", symbol: "$" },
  { code: "BH", country: "Bahrain", flag: "🇧🇭", dialCode: "973", fullCode: "+973", minLength: 8, maxLength: 8, currency: "BHD", symbol: ".د.ब" },
  { code: "BD", country: "Bangladesh", flag: "🇧🇩", dialCode: "880", fullCode: "+880", minLength: 10, maxLength: 10, currency: "BDT", symbol: "৳" },
  { code: "BB", country: "Barbados", flag: "🇧🇧", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "BBD", symbol: "$" },
  { code: "BY", country: "Belarus", flag: "🇧🇾", dialCode: "375", fullCode: "+375", minLength: 9, maxLength: 9, currency: "BYN", symbol: "Br" },
  { code: "BE", country: "Belgium", flag: "🇧🇪", dialCode: "32", fullCode: "+32", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "BZ", country: "Belize", flag: "🇧🇿", dialCode: "501", fullCode: "+501", minLength: 7, maxLength: 7, currency: "BZD", symbol: "$" },
  { code: "BJ", country: "Benin", flag: "🇧🇯", dialCode: "229", fullCode: "+229", minLength: 8, maxLength: 8, currency: "XOF", symbol: "CFA" },
  { code: "BM", country: "Bermuda", flag: "🇧🇲", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "BMD", symbol: "$" },
  { code: "BT", country: "Bhutan", flag: "🇧🇹", dialCode: "975", fullCode: "+975", minLength: 8, maxLength: 8, currency: "BTN", symbol: "Nu." },
  { code: "BO", country: "Bolivia", flag: "🇧🇴", dialCode: "591", fullCode: "+591", minLength: 8, maxLength: 8, currency: "BOB", symbol: "Bs." },
  { code: "BA", country: "Bosnia and Herzegovina", flag: "🇧🇦", dialCode: "387", fullCode: "+387", minLength: 8, maxLength: 9, currency: "BAM", symbol: "KM" },
  { code: "BW", country: "Botswana", flag: "🇧🇼", dialCode: "267", fullCode: "+267", minLength: 8, maxLength: 8, currency: "BWP", symbol: "P" },
  { code: "BR", country: "Brazil", flag: "🇧🇷", dialCode: "55", fullCode: "+55", minLength: 10, maxLength: 11, currency: "BRL", symbol: "R$" },
  { code: "BN", country: "Brunei", flag: "🇧🇳", dialCode: "673", fullCode: "+673", minLength: 7, maxLength: 7, currency: "BND", symbol: "$" },
  { code: "BG", country: "Bulgaria", flag: "🇧🇬", dialCode: "359", fullCode: "+359", minLength: 8, maxLength: 9, currency: "BGN", symbol: "лв" },
  { code: "BF", country: "Burkina Faso", flag: "🇧🇫", dialCode: "226", fullCode: "+226", minLength: 8, maxLength: 8, currency: "XOF", symbol: "CFA" },
  { code: "BI", country: "Burundi", flag: "🇧🇮", dialCode: "257", fullCode: "+257", minLength: 8, maxLength: 8, currency: "BIF", symbol: "FBu" },
  { code: "KH", country: "Cambodia", flag: "🇰🇭", dialCode: "855", fullCode: "+855", minLength: 8, maxLength: 9, currency: "KHR", symbol: "៛" },
  { code: "CM", country: "Cameroon", flag: "🇨🇲", dialCode: "237", fullCode: "+237", minLength: 9, maxLength: 9, currency: "XAF", symbol: "FCFA" },
  { code: "CA", country: "Canada", flag: "🇨🇦", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "CAD", symbol: "$" },
  { code: "CV", country: "Cape Verde", flag: "🇨🇻", dialCode: "238", fullCode: "+238", minLength: 7, maxLength: 7, currency: "CVE", symbol: "$" },
  { code: "KY", country: "Cayman Islands", flag: "🇰🇾", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "KYD", symbol: "$" },
  { code: "CF", country: "Central African Republic", flag: "🇨🇫", dialCode: "236", fullCode: "+236", minLength: 8, maxLength: 8, currency: "XAF", symbol: "FCFA" },
  { code: "TD", country: "Chad", flag: "🇹🇩", dialCode: "235", fullCode: "+235", minLength: 8, maxLength: 8, currency: "XAF", symbol: "FCFA" },
  { code: "CL", country: "Chile", flag: "🇨🇱", dialCode: "56", fullCode: "+56", minLength: 9, maxLength: 9, currency: "CLP", symbol: "$" },
  { code: "CN", country: "China", flag: "🇨🇳", dialCode: "86", fullCode: "+86", minLength: 11, maxLength: 11, currency: "CNY", symbol: "¥" },
  { code: "CO", country: "Colombia", flag: "🇨🇴", dialCode: "57", fullCode: "+57", minLength: 10, maxLength: 10, currency: "COP", symbol: "$" },
  { code: "KM", country: "Comoros", flag: "🇰🇲", dialCode: "269", fullCode: "+269", minLength: 7, maxLength: 7, currency: "KMF", symbol: "CF" },
  { code: "CG", country: "Congo", flag: "🇨🇬", dialCode: "242", fullCode: "+242", minLength: 9, maxLength: 9, currency: "XAF", symbol: "FCFA" },
  { code: "CD", country: "Congo, DR", flag: "🇨🇩", dialCode: "243", fullCode: "+243", minLength: 9, maxLength: 9, currency: "CDF", symbol: "FC" },
  { code: "CK", country: "Cook Islands", flag: "🇨🇰", dialCode: "682", fullCode: "+682", minLength: 5, maxLength: 5, currency: "NZD", symbol: "$" },
  { code: "CR", country: "Costa Rica", flag: "🇨🇷", dialCode: "506", fullCode: "+506", minLength: 8, maxLength: 8, currency: "CRC", symbol: "₡" },
  { code: "CI", country: "Cote d'Ivoire", flag: "🇨🇮", dialCode: "225", fullCode: "+225", minLength: 8, maxLength: 10, currency: "XOF", symbol: "CFA" },
  { code: "HR", country: "Croatia", flag: "🇭🇷", dialCode: "385", fullCode: "+385", minLength: 8, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "CU", country: "Cuba", flag: "🇨🇺", dialCode: "53", fullCode: "+53", minLength: 8, maxLength: 8, currency: "CUP", symbol: "$" },
  { code: "CW", country: "Curacao", flag: "🇨🇼", dialCode: "599", fullCode: "+599", minLength: 7, maxLength: 7, currency: "ANG", symbol: "ƒ" },
  { code: "CY", country: "Cyprus", flag: "🇨🇾", dialCode: "357", fullCode: "+357", minLength: 8, maxLength: 8, currency: "EUR", symbol: "€" },
  { code: "CZ", country: "Czech Republic", flag: "🇨🇿", dialCode: "420", fullCode: "+420", minLength: 9, maxLength: 9, currency: "CZK", symbol: "Kč" },
  { code: "DK", country: "Denmark", flag: "🇩🇰", dialCode: "45", fullCode: "+45", minLength: 8, maxLength: 8, currency: "DKK", symbol: "kr" },
  { code: "DJ", country: "Djibouti", flag: "🇩🇯", dialCode: "253", fullCode: "+253", minLength: 8, maxLength: 8, currency: "DJF", symbol: "Fdj" },
  { code: "DM", country: "Dominica", flag: "🇩🇲", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "XCD", symbol: "$" },
  { code: "DO", country: "Dominican Republic", flag: "🇩🇴", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "DOP", symbol: "$" },
  { code: "EC", country: "Ecuador", flag: "🇪🇨", dialCode: "593", fullCode: "+593", minLength: 9, maxLength: 9, currency: "USD", symbol: "$" },
  { code: "EG", country: "Egypt", flag: "🇪🇬", dialCode: "20", fullCode: "+20", minLength: 10, maxLength: 10, currency: "EGP", symbol: "E£" },
  { code: "SV", country: "El Salvador", flag: "🇸🇻", dialCode: "503", fullCode: "+503", minLength: 8, maxLength: 8, currency: "USD", symbol: "$" },
  { code: "GQ", country: "Equatorial Guinea", flag: "🇬🇶", dialCode: "240", fullCode: "+240", minLength: 9, maxLength: 9, currency: "XAF", symbol: "FCFA" },
  { code: "ER", country: "Eritrea", flag: "🇪🇷", dialCode: "291", fullCode: "+291", minLength: 7, maxLength: 7, currency: "ERN", symbol: "Nfk" },
  { code: "EE", country: "Estonia", flag: "🇪🇪", dialCode: "372", fullCode: "+372", minLength: 7, maxLength: 8, currency: "EUR", symbol: "€" },
  { code: "ET", country: "Ethiopia", flag: "🇪🇹", dialCode: "251", fullCode: "+251", minLength: 9, maxLength: 9, currency: "ETB", symbol: "Br" },
  { code: "FK", country: "Falkland Islands", flag: "🇫🇰", dialCode: "500", fullCode: "+500", minLength: 5, maxLength: 5, currency: "FKP", symbol: "£" },
  { code: "FO", country: "Faroe Islands", flag: "🇫🇴", dialCode: "298", fullCode: "+298", minLength: 6, maxLength: 6, currency: "DKK", symbol: "kr" },
  { code: "FJ", country: "Fiji", flag: "🇫🇯", dialCode: "679", fullCode: "+679", minLength: 7, maxLength: 7, currency: "FJD", symbol: "$" },
  { code: "FI", country: "Finland", flag: "🇫🇮", dialCode: "358", fullCode: "+358", minLength: 5, maxLength: 12, currency: "EUR", symbol: "€" },
  { code: "FR", country: "France", flag: "🇫🇷", dialCode: "33", fullCode: "+33", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "GF", country: "French Guiana", flag: "🇬🇫", dialCode: "594", fullCode: "+594", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "PF", country: "French Polynesia", flag: "🇵🇫", dialCode: "689", fullCode: "+689", minLength: 8, maxLength: 8, currency: "XPF", symbol: "₣" },
  { code: "GA", country: "Gabon", flag: "🇬🇦", dialCode: "241", fullCode: "+241", minLength: 8, maxLength: 8, currency: "XAF", symbol: "FCFA" },
  { code: "GM", country: "Gambia", flag: "🇬🇲", dialCode: "220", fullCode: "+220", minLength: 7, maxLength: 7, currency: "GMD", symbol: "D" },
  { code: "GE", country: "Georgia", flag: "🇬🇪", dialCode: "995", fullCode: "+995", minLength: 9, maxLength: 9, currency: "GEL", symbol: "₾" },
  { code: "DE", country: "Germany", flag: "🇩🇪", dialCode: "49", fullCode: "+49", minLength: 10, maxLength: 10, currency: "EUR", symbol: "€" },
  { code: "GH", country: "Ghana", flag: "🇬🇭", dialCode: "233", fullCode: "+233", minLength: 9, maxLength: 9, currency: "GHS", symbol: "GH₵" },
  { code: "GI", country: "Gibraltar", flag: "🇬🇮", dialCode: "350", fullCode: "+350", minLength: 8, maxLength: 8, currency: "GIP", symbol: "£" },
  { code: "GR", country: "Greece", flag: "🇬🇷", dialCode: "30", fullCode: "+30", minLength: 10, maxLength: 10, currency: "EUR", symbol: "€" },
  { code: "GL", country: "Greenland", flag: "🇬🇱", dialCode: "299", fullCode: "+299", minLength: 6, maxLength: 6, currency: "DKK", symbol: "kr" },
  { code: "GD", country: "Grenada", flag: "🇬🇩", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "XCD", symbol: "$" },
  { code: "GP", country: "Guadeloupe", flag: "🇬🇵", dialCode: "590", fullCode: "+590", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "GU", country: "Guam", flag: "🇬🇺", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "USD", symbol: "$" },
  { code: "GT", country: "Guatemala", flag: "🇬🇹", dialCode: "502", fullCode: "+502", minLength: 8, maxLength: 8, currency: "GTQ", symbol: "Q" },
  { code: "GN", country: "Guinea", flag: "🇬🇳", dialCode: "224", fullCode: "+224", minLength: 9, maxLength: 9, currency: "GNF", symbol: "FG" },
  { code: "GW", country: "Guinea-Bissau", flag: "🇬🇼", dialCode: "245", fullCode: "+245", minLength: 9, maxLength: 9, currency: "XOF", symbol: "CFA" },
  { code: "GY", country: "Guyana", flag: "🇬🇾", dialCode: "592", fullCode: "+592", minLength: 7, maxLength: 7, currency: "GYD", symbol: "$" },
  { code: "HT", country: "Haiti", flag: "🇭🇹", dialCode: "509", fullCode: "+509", minLength: 8, maxLength: 8, currency: "HTG", symbol: "G" },
  { code: "HN", country: "Honduras", flag: "🇭🇳", dialCode: "504", fullCode: "+504", minLength: 8, maxLength: 8, currency: "HNL", symbol: "L" },
  { code: "HK", country: "Hong Kong", flag: "🇭🇰", dialCode: "852", fullCode: "+852", minLength: 8, maxLength: 8, currency: "HKD", symbol: "$" },
  { code: "HU", country: "Hungary", flag: "🇭🇺", dialCode: "36", fullCode: "+36", minLength: 9, maxLength: 9, currency: "HUF", symbol: "Ft" },
  { code: "IS", country: "Iceland", flag: "🇮🇸", dialCode: "354", fullCode: "+354", minLength: 7, maxLength: 7, currency: "ISK", symbol: "kr" },
  { code: "IN", country: "India", flag: "🇮🇳", dialCode: "91", fullCode: "+91", minLength: 10, maxLength: 10, currency: "INR", symbol: "₹" },
  { code: "ID", country: "Indonesia", flag: "🇮🇩", dialCode: "62", fullCode: "+62", minLength: 9, maxLength: 12, currency: "IDR", symbol: "Rp" },
  { code: "IR", country: "Iran", flag: "🇮🇷", dialCode: "98", fullCode: "+98", minLength: 10, maxLength: 10, currency: "IRR", symbol: "﷼" },
  { code: "IQ", country: "Iraq", flag: "🇮🇶", dialCode: "964", fullCode: "+964", minLength: 10, maxLength: 10, currency: "IQD", symbol: "ع.د" },
  { code: "IE", country: "Ireland", flag: "🇮🇪", dialCode: "353", fullCode: "+353", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "IL", country: "Israel", flag: "🇮🇱", dialCode: "972", fullCode: "+972", minLength: 9, maxLength: 9, currency: "ILS", symbol: "₪" },
  { code: "IT", country: "Italy", flag: "🇮🇹", dialCode: "39", fullCode: "+39", minLength: 10, maxLength: 10, currency: "EUR", symbol: "€" },
  { code: "JM", country: "Jamaica", flag: "🇯🇲", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "JMD", symbol: "$" },
  { code: "JP", country: "Japan", flag: "🇯🇵", dialCode: "81", fullCode: "+81", minLength: 10, maxLength: 10, currency: "JPY", symbol: "¥" },
  { code: "JO", country: "Jordan", flag: "🇯🇴", dialCode: "962", fullCode: "+962", minLength: 9, maxLength: 9, currency: "JOD", symbol: "د.ا" },
  { code: "KZ", country: "Kazakhstan", flag: "🇰🇿", dialCode: "7", fullCode: "+7", minLength: 10, maxLength: 10, currency: "KZT", symbol: "₸" },
  { code: "KE", country: "Kenya", flag: "🇰🇪", dialCode: "254", fullCode: "+254", minLength: 9, maxLength: 9, currency: "KES", symbol: "KSh" },
  { code: "KI", country: "Kiribati", flag: "🇰🇮", dialCode: "686", fullCode: "+686", minLength: 5, maxLength: 8, currency: "AUD", symbol: "$" },
  { code: "KP", country: "North Korea", flag: "🇰🇵", dialCode: "850", fullCode: "+850", minLength: 8, maxLength: 10, currency: "KPW", symbol: "₩" },
  { code: "KR", country: "South Korea", flag: "🇰🇷", dialCode: "82", fullCode: "+82", minLength: 9, maxLength: 10, currency: "KRW", symbol: "₩" },
  { code: "KW", country: "Kuwait", flag: "🇰🇼", dialCode: "965", fullCode: "+965", minLength: 8, maxLength: 8, currency: "KWD", symbol: "د.क" },
  { code: "KG", country: "Kyrgyzstan", flag: "🇰🇬", dialCode: "996", fullCode: "+996", minLength: 9, maxLength: 9, currency: "KGS", symbol: "лв" },
  { code: "LA", country: "Laos", flag: "🇱🇦", dialCode: "856", fullCode: "+856", minLength: 8, maxLength: 10, currency: "LAK", symbol: "₭" },
  { code: "LV", country: "Latvia", flag: "🇱🇻", dialCode: "371", fullCode: "+371", minLength: 8, maxLength: 8, currency: "EUR", symbol: "€" },
  { code: "LB", country: "Lebanon", flag: "🇱🇧", dialCode: "961", fullCode: "+961", minLength: 7, maxLength: 8, currency: "LBP", symbol: "L£" },
  { code: "LS", country: "Lesotho", flag: "🇱🇸", dialCode: "266", fullCode: "+266", minLength: 8, maxLength: 8, currency: "LSL", symbol: "L" },
  { code: "LR", country: "Liberia", flag: "🇱🇷", dialCode: "231", fullCode: "+231", minLength: 7, maxLength: 9, currency: "LRD", symbol: "$" },
  { code: "LY", country: "Libya", flag: "🇱🇾", dialCode: "218", fullCode: "+218", minLength: 9, maxLength: 9, currency: "LYD", symbol: "ل.د" },
  { code: "LI", country: "Liechtenstein", flag: "🇱🇮", dialCode: "423", fullCode: "+423", minLength: 7, maxLength: 7, currency: "CHF", symbol: "CHf" },
  { code: "LT", country: "Lithuania", flag: "🇱🇹", dialCode: "370", fullCode: "+370", minLength: 8, maxLength: 8, currency: "EUR", symbol: "€" },
  { code: "LU", country: "Luxembourg", flag: "🇱🇺", dialCode: "352", fullCode: "+352", minLength: 8, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "MO", country: "Macau", flag: "🇲🇴", dialCode: "853", fullCode: "+853", minLength: 8, maxLength: 8, currency: "MOP", symbol: "P" },
  { code: "MK", country: "Macedonia", flag: "🇲🇰", dialCode: "389", fullCode: "+389", minLength: 8, maxLength: 8, currency: "MKD", symbol: "ден" },
  { code: "MG", country: "Madagascar", flag: "🇲🇬", dialCode: "261", fullCode: "+261", minLength: 9, maxLength: 9, currency: "MGA", symbol: "Ar" },
  { code: "MW", country: "Malawi", flag: "🇲🇼", dialCode: "265", fullCode: "+265", minLength: 7, maxLength: 9, currency: "MWK", symbol: "MK" },
  { code: "MY", country: "Malaysia", flag: "🇲🇾", dialCode: "60", fullCode: "+60", minLength: 7, maxLength: 10, currency: "MYR", symbol: "RM" },
  { code: "MV", country: "Maldives", flag: "🇲🇻", dialCode: "960", fullCode: "+960", minLength: 7, maxLength: 7, currency: "MVR", symbol: ".ރ" },
  { code: "ML", country: "Mali", flag: "🇲🇱", dialCode: "223", fullCode: "+223", minLength: 8, maxLength: 8, currency: "XOF", symbol: "CFA" },
  { code: "MT", country: "Malta", flag: "🇲🇹", dialCode: "356", fullCode: "+356", minLength: 8, maxLength: 8, currency: "EUR", symbol: "€" },
  { code: "MH", country: "Marshall Islands", flag: "🇲🇭", dialCode: "692", fullCode: "+692", minLength: 7, maxLength: 7, currency: "USD", symbol: "$" },
  { code: "MQ", country: "Martinique", flag: "🇲🇶", dialCode: "596", fullCode: "+596", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "MR", country: "Mauritania", flag: "🇲🇷", dialCode: "222", fullCode: "+222", minLength: 8, maxLength: 8, currency: "MRU", symbol: "UM" },
  { code: "MU", country: "Mauritius", flag: "🇲🇺", dialCode: "230", fullCode: "+230", minLength: 8, maxLength: 8, currency: "MUR", symbol: "₨" },
  { code: "YT", country: "Mayotte", flag: "🇾🇹", dialCode: "262", fullCode: "+262", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "MX", country: "Mexico", flag: "🇲🇽", dialCode: "52", fullCode: "+52", minLength: 10, maxLength: 10, currency: "MXN", symbol: "$" },
  { code: "FM", country: "Micronesia", flag: "🇫🇲", dialCode: "691", fullCode: "+691", minLength: 7, maxLength: 7, currency: "USD", symbol: "$" },
  { code: "MD", country: "Moldova", flag: "🇲🇩", dialCode: "373", fullCode: "+373", minLength: 8, maxLength: 8, currency: "MDL", symbol: "L" },
  { code: "MC", country: "Monaco", flag: "🇲🇨", dialCode: "377", fullCode: "+377", minLength: 8, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "MN", country: "Mongolia", flag: "🇲🇳", dialCode: "976", fullCode: "+976", minLength: 8, maxLength: 8, currency: "MNT", symbol: "₮" },
  { code: "ME", country: "Montenegro", flag: "🇲🇪", dialCode: "382", fullCode: "+382", minLength: 8, maxLength: 8, currency: "EUR", symbol: "€" },
  { code: "MS", country: "Montserrat", flag: "🇲🇸", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "XCD", symbol: "$" },
  { code: "MA", country: "Morocco", flag: "🇲🇦", dialCode: "212", fullCode: "+212", minLength: 9, maxLength: 9, currency: "MAD", symbol: "د.م." },
  { code: "MZ", country: "Mozambique", flag: "🇲🇿", dialCode: "258", fullCode: "+258", minLength: 9, maxLength: 9, currency: "MZN", symbol: "MT" },
  { code: "MM", country: "Myanmar", flag: "🇲🇲", dialCode: "95", fullCode: "+95", minLength: 8, maxLength: 10, currency: "MMK", symbol: "Ks" },
  { code: "NA", country: "Namibia", flag: "🇳🇦", dialCode: "264", fullCode: "+264", minLength: 8, maxLength: 9, currency: "NAD", symbol: "$" },
  { code: "NR", country: "Nauru", flag: "🇳🇷", dialCode: "674", fullCode: "+674", minLength: 7, maxLength: 7, currency: "AUD", symbol: "$" },
  { code: "NP", country: "Nepal", flag: "🇳🇵", dialCode: "977", fullCode: "+977", minLength: 10, maxLength: 10, currency: "NPR", symbol: "₨" },
  { code: "NL", country: "Netherlands", flag: "🇳🇱", dialCode: "31", fullCode: "+31", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "NC", country: "New Caledonia", flag: "🇳🇨", dialCode: "687", fullCode: "+687", minLength: 6, maxLength: 6, currency: "XPF", symbol: "₣" },
  { code: "NZ", country: "New Zealand", flag: "🇳🇿", dialCode: "64", fullCode: "+64", minLength: 8, maxLength: 10, currency: "NZD", symbol: "$" },
  { code: "NI", country: "Nicaragua", flag: "🇳🇮", dialCode: "505", fullCode: "+505", minLength: 8, maxLength: 8, currency: "NIO", symbol: "C$" },
  { code: "NE", country: "Niger", flag: "🇳🇪", dialCode: "227", fullCode: "+227", minLength: 8, maxLength: 8, currency: "XOF", symbol: "CFA" },
  { code: "NG", country: "Nigeria", flag: "🇳🇬", dialCode: "234", fullCode: "+234", minLength: 10, maxLength: 10, currency: "NGN", symbol: "₦" },
  { code: "NU", country: "Niue", flag: "🇳🇺", dialCode: "683", fullCode: "+683", minLength: 4, maxLength: 4, currency: "NZD", symbol: "$" },
  { code: "NF", country: "Norfolk Island", flag: "🇳🇫", dialCode: "672", fullCode: "+672", minLength: 6, maxLength: 6, currency: "AUD", symbol: "$" },
  { code: "MP", country: "Northern Mariana Islands", flag: "🇲🇵", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "USD", symbol: "$" },
  { code: "NO", country: "Norway", flag: "🇳🇴", dialCode: "47", fullCode: "+47", minLength: 8, maxLength: 8, currency: "NOK", symbol: "kr" },
  { code: "OM", country: "Oman", flag: "🇴🇲", dialCode: "968", fullCode: "+968", minLength: 8, maxLength: 8, currency: "OMR", symbol: "ر.ع." },
  { code: "PK", country: "Pakistan", flag: "🇵🇰", dialCode: "92", fullCode: "+92", minLength: 10, maxLength: 10, currency: "PKR", symbol: "₨" },
  { code: "PW", country: "Palau", flag: "🇵🇼", dialCode: "680", fullCode: "+680", minLength: 7, maxLength: 7, currency: "USD", symbol: "$" },
  { code: "PS", country: "Palestine", flag: "🇵🇸", dialCode: "970", fullCode: "+970", minLength: 9, maxLength: 9, currency: "ILS", symbol: "₪" },
  { code: "PA", country: "Panama", flag: "🇵🇦", dialCode: "507", fullCode: "+507", minLength: 8, maxLength: 8, currency: "PAB", symbol: "B/." },
  { code: "PG", country: "Papua New Guinea", flag: "🇵🇬", dialCode: "675", fullCode: "+675", minLength: 8, maxLength: 8, currency: "PGK", symbol: "K" },
  { code: "PY", country: "Paraguay", flag: "🇵🇾", dialCode: "595", fullCode: "+595", minLength: 9, maxLength: 9, currency: "PYG", symbol: "₲" },
  { code: "PE", country: "Peru", flag: "🇵🇪", dialCode: "51", fullCode: "+51", minLength: 9, maxLength: 9, currency: "PEN", symbol: "S/." },
  { code: "PH", country: "Philippines", flag: "🇵🇭", dialCode: "63", fullCode: "+63", minLength: 10, maxLength: 10, currency: "PHP", symbol: "₱" },
  { code: "PL", country: "Poland", flag: "🇵🇱", dialCode: "48", fullCode: "+48", minLength: 9, maxLength: 9, currency: "PLN", symbol: "zł" },
  { code: "PT", country: "Portugal", flag: "🇵🇹", dialCode: "351", fullCode: "+351", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "PR", country: "Puerto Rico", flag: "🇵🇷", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "USD", symbol: "$" },
  { code: "QA", country: "Qatar", flag: "🇶🇦", dialCode: "974", fullCode: "+974", minLength: 8, maxLength: 8, currency: "QAR", symbol: "ر.ق" },
  { code: "RE", country: "Reunion", flag: "🇷🇪", dialCode: "262", fullCode: "+262", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "RO", country: "Romania", flag: "🇷🇴", dialCode: "40", fullCode: "+40", minLength: 9, maxLength: 9, currency: "RON", symbol: "lei" },
  { code: "RU", country: "Russia", flag: "🇷🇺", dialCode: "7", fullCode: "+7", minLength: 10, maxLength: 10, currency: "RUB", symbol: "₽" },
  { code: "RW", country: "Rwanda", flag: "🇷🇼", dialCode: "250", fullCode: "+250", minLength: 9, maxLength: 9, currency: "RWF", symbol: "FRw" },
  { code: "BL", country: "Saint Barthelemy", flag: "🇧🇱", dialCode: "590", fullCode: "+590", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "SH", country: "Saint Helena", flag: "🇸🇭", dialCode: "290", fullCode: "+290", minLength: 4, maxLength: 4, currency: "SHP", symbol: "£" },
  { code: "KN", country: "Saint Kitts and Nevis", flag: "🇰🇳", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "XCD", symbol: "$" },
  { code: "LC", country: "Saint Lucia", flag: "🇱🇨", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "XCD", symbol: "$" },
  { code: "MF", country: "Saint Martin", flag: "🇲🇫", dialCode: "590", fullCode: "+590", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "PM", country: "Saint Pierre and Miquelon", flag: "🇵🇲", dialCode: "508", fullCode: "+508", minLength: 6, maxLength: 6, currency: "EUR", symbol: "€" },
  { code: "VC", country: "Saint Vincent and the Grenadines", flag: "🇻🇨", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "XCD", symbol: "$" },
  { code: "WS", country: "Samoa", flag: "🇼🇸", dialCode: "685", fullCode: "+685", minLength: 7, maxLength: 7, currency: "WST", symbol: "T" },
  { code: "SM", country: "San Marino", flag: "🇸🇲", dialCode: "378", fullCode: "+378", minLength: 10, maxLength: 10, currency: "EUR", symbol: "€" },
  { code: "ST", country: "Sao Tome and Principe", flag: "🇸🇹", dialCode: "239", fullCode: "+239", minLength: 7, maxLength: 7, currency: "STN", symbol: "Db" },
  { code: "SA", country: "Saudi Arabia", flag: "🇸🇦", dialCode: "966", fullCode: "+966", minLength: 9, maxLength: 9, currency: "SAR", symbol: "ر.س" },
  { code: "SN", country: "Senegal", flag: "🇸🇳", dialCode: "221", fullCode: "+221", minLength: 9, maxLength: 9, currency: "XOF", symbol: "CFA" },
  { code: "RS", country: "Serbia", flag: "🇷🇸", dialCode: "381", fullCode: "+381", minLength: 8, maxLength: 9, currency: "RSD", symbol: "дин." },
  { code: "SC", country: "Seychelles", flag: "🇸🇨", dialCode: "248", fullCode: "+248", minLength: 7, maxLength: 7, currency: "SCR", symbol: "₨" },
  { code: "SL", country: "Sierra Leone", flag: "🇸🇱", dialCode: "232", fullCode: "+232", minLength: 8, maxLength: 8, currency: "SLL", symbol: "Le" },
  { code: "SG", country: "Singapore", flag: "🇸🇬", dialCode: "65", fullCode: "+65", minLength: 8, maxLength: 8, currency: "SGD", symbol: "$" },
  { code: "SX", country: "Sint Maarten", flag: "🇸🇽", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "ANG", symbol: "ƒ" },
  { code: "SK", country: "Slovakia", flag: "🇸🇰", dialCode: "421", fullCode: "+421", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "SI", country: "Slovenia", flag: "🇸🇮", dialCode: "386", fullCode: "+386", minLength: 8, maxLength: 8, currency: "EUR", symbol: "€" },
  { code: "SB", country: "Solomon Islands", flag: "🇸🇧", dialCode: "677", fullCode: "+677", minLength: 7, maxLength: 7, currency: "SBD", symbol: "$" },
  { code: "SO", country: "Somalia", flag: "🇸🇴", dialCode: "252", fullCode: "+252", minLength: 8, maxLength: 8, currency: "SOS", symbol: "Sh" },
  { code: "ZA", country: "South Africa", flag: "🇿🇦", dialCode: "27", fullCode: "+27", minLength: 9, maxLength: 9, currency: "ZAR", symbol: "R" },
  { code: "SS", country: "South Sudan", flag: "🇸🇸", dialCode: "211", fullCode: "+211", minLength: 9, maxLength: 9, currency: "SSP", symbol: "£" },
  { code: "ES", country: "Spain", flag: "🇪🇸", dialCode: "34", fullCode: "+34", minLength: 9, maxLength: 9, currency: "EUR", symbol: "€" },
  { code: "LK", country: "Sri Lanka", flag: "🇱🇰", dialCode: "94", fullCode: "+94", minLength: 9, maxLength: 9, currency: "LKR", symbol: "Rs" },
  { code: "SD", country: "Sudan", flag: "🇸🇩", dialCode: "249", fullCode: "+249", minLength: 9, maxLength: 9, currency: "SDG", symbol: "ج.س." },
  { code: "SR", country: "Suriname", flag: "🇸🇷", dialCode: "597", fullCode: "+597", minLength: 7, maxLength: 7, currency: "SRD", symbol: "$" },
  { code: "SZ", country: "Swaziland", flag: "🇸🇿", dialCode: "268", fullCode: "+268", minLength: 8, maxLength: 8, currency: "SZL", symbol: "L" },
  { code: "SE", country: "Sweden", flag: "🇸🇪", dialCode: "46", fullCode: "+46", minLength: 7, maxLength: 13, currency: "SEK", symbol: "kr" },
  { code: "CH", country: "Switzerland", flag: "🇨🇭", dialCode: "41", fullCode: "+41", minLength: 9, maxLength: 9, currency: "CHF", symbol: "CHf" },
  { code: "SY", country: "Syria", flag: "🇸🇾", dialCode: "963", fullCode: "+963", minLength: 9, maxLength: 9, currency: "SYP", symbol: "£" },
  { code: "TW", country: "Taiwan", flag: "🇹🇼", dialCode: "886", fullCode: "+886", minLength: 9, maxLength: 9, currency: "TWD", symbol: "NT$" },
  { code: "TJ", country: "Tajikistan", flag: "🇹🇯", dialCode: "992", fullCode: "+992", minLength: 9, maxLength: 9, currency: "TJS", symbol: "ЅМ" },
  { code: "TZ", country: "Tanzania", flag: "🇹🇿", dialCode: "255", fullCode: "+255", minLength: 9, maxLength: 9, currency: "TZS", symbol: "Sh" },
  { code: "TH", country: "Thailand", flag: "🇹🇭", dialCode: "66", fullCode: "+66", minLength: 9, maxLength: 9, currency: "THB", symbol: "฿" },
  { code: "TL", country: "Timor-Leste", flag: "🇹🇱", dialCode: "670", fullCode: "+670", minLength: 8, maxLength: 8, currency: "USD", symbol: "$" },
  { code: "TG", country: "Togo", flag: "🇹🇬", dialCode: "228", fullCode: "+228", minLength: 8, maxLength: 8, currency: "XOF", symbol: "CFA" },
  { code: "TK", country: "Tokelau", flag: "🇹🇰", dialCode: "690", fullCode: "+690", minLength: 4, maxLength: 4, currency: "NZD", symbol: "$" },
  { code: "TO", country: "Tonga", flag: "🇹🇴", dialCode: "676", fullCode: "+676", minLength: 5, maxLength: 5, currency: "TOP", symbol: "T$" },
  { code: "TT", country: "Trinidad and Tobago", flag: "🇹🇹", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "TTD", symbol: "$" },
  { code: "TN", country: "Tunisia", flag: "🇹🇳", dialCode: "216", fullCode: "+216", minLength: 8, maxLength: 8, currency: "TND", symbol: "د.त" },
  { code: "TR", country: "Turkey", flag: "🇹🇷", dialCode: "90", fullCode: "+90", minLength: 10, maxLength: 10, currency: "TRY", symbol: "₺" },
  { code: "TM", country: "Turkmenistan", flag: "🇹🇲", dialCode: "993", fullCode: "+993", minLength: 8, maxLength: 8, currency: "TMT", symbol: "m" },
  { code: "TC", country: "Turks and Caicos Islands", flag: "🇹🇨", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "USD", symbol: "$" },
  { code: "TV", country: "Tuvalu", flag: "🇹🇻", dialCode: "688", fullCode: "+688", minLength: 5, maxLength: 5, currency: "AUD", symbol: "$" },
  { code: "UG", country: "Uganda", flag: "🇺🇬", dialCode: "256", fullCode: "+256", minLength: 9, maxLength: 9, currency: "UGX", symbol: "USh" },
  { code: "UA", country: "Ukraine", flag: "🇺🇦", dialCode: "380", fullCode: "+380", minLength: 9, maxLength: 9, currency: "UAH", symbol: "₴" },
  { code: "AE", country: "United Arab Emirates", flag: "🇦🇪", dialCode: "971", fullCode: "+971", minLength: 9, maxLength: 9, currency: "AED", symbol: "د.إ" },
  { code: "GB", country: "United Kingdom", flag: "🇬🇧", dialCode: "44", fullCode: "+44", minLength: 10, maxLength: 10, currency: "GBP", symbol: "£" },
  { code: "US", country: "United States", flag: "🇺🇸", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "USD", symbol: "$" },
  { code: "UY", country: "Uruguay", flag: "🇺🇾", dialCode: "598", fullCode: "+598", minLength: 8, maxLength: 8, currency: "UYU", symbol: "$U" },
  { code: "UZ", country: "Uzbekistan", flag: "🇺🇿", dialCode: "998", fullCode: "+998", minLength: 9, maxLength: 9, currency: "UZS", symbol: "лв" },
  { code: "VU", country: "Vanuatu", flag: "🇻🇺", dialCode: "678", fullCode: "+678", minLength: 7, maxLength: 7, currency: "VUV", symbol: "VT" },
  { code: "VE", country: "Venezuela", flag: "🇻🇪", dialCode: "58", fullCode: "+58", minLength: 10, maxLength: 10, currency: "VES", symbol: "Bs.S" },
  { code: "VN", country: "Vietnam", flag: "🇻🇳", dialCode: "84", fullCode: "+84", minLength: 10, maxLength: 10, currency: "VND", symbol: "₫" },
  { code: "VG", country: "British Virgin Islands", flag: "🇻🇬", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "USD", symbol: "$" },
  { code: "VI", country: "US Virgin Islands", flag: "🇻🇮", dialCode: "1", fullCode: "+1", minLength: 10, maxLength: 10, currency: "USD", symbol: "$" },
  { code: "WF", country: "Wallis and Futuna", flag: "🇼🇫", dialCode: "681", fullCode: "+681", minLength: 6, maxLength: 6, currency: "XPF", symbol: "₣" },
  { code: "YE", country: "Yemen", flag: "🇾🇪", dialCode: "967", fullCode: "+967", minLength: 9, maxLength: 9, currency: "YER", symbol: "﷼" },
  { code: "ZM", country: "Zambia", flag: "🇿🇲", dialCode: "260", fullCode: "+260", minLength: 9, maxLength: 9, currency: "ZMW", symbol: "ZK" },
  { code: "ZW", country: "Zimbabwe", flag: "🇿🇼", dialCode: "263", fullCode: "+263", minLength: 9, maxLength: 9, currency: "ZWL", symbol: "$" },
];
